export const CREATE_COURSE = "CREATE_COURSE";
export const LOAD_COURSES_SUCCESS = "LOAD_COURSES_SUCCESS";
export const LOAD_AUTHORS_SUCESS = "LOAD_AUTHORS_SUCESS";
export const SAVE_COURSE_SUCCESS = "SAVE_COURSE_SUCCESS";
export const CREATE_COURSE_SUCCESS = "CREATE_COURSE_SUCCESS";
export const BEGIN_API_CALL = "BEGIN_API_CALL";
export const API_CALL_ERROR = "API_CALL_ERROR";

export const DELETE_COURSE_OPTIMISTIC = "DELETE_COURSE_OPTIMISTIC";
